### ISSUE TITLE
个人数据分析

### ISSUE THREAD

**Issue by derekcoder** [CoderxApp/Feedback#1]
个人数据分析页面 + 支持分享

**Comment by derekcoder** [comment]
> P系列 Star按钮显示问题

是指 Star 按钮显示有问题吗？可以上传个界面吗？

**Comment by sauchye** [comment]
>  其实不影响使用 o(╯□╰)o

![star](https://user-images.githubusercontent.com/4171847/51304629-a139ed00-1a73-11e9-8581-c381a22e7a55.jpg)

![following](https://user-images.githubusercontent.com/4171847/51304646-ab5beb80-1a73-11e9-9d7d-670f98381ef0.jpg)

**Comment by derekcoder** [comment]
@sauchye 这是故意设计成这样的😂
