### ISSUE TITLE
阅读代码业极其反人类

### ISSUE THREAD

**Issue by SinCheung** [CoderxApp/Feedback#74]
以前采用push的代码vc不好吗？现在改成present的，还不支持新系统手势dismiss，极其难用，增加点击难度，差评。

iPhone 8 13.3.1 - V3.3.2(349)

**Comment by derekcoder** [comment]
下个版本 3.4.0 中，阅读代码时会支持系统手势下拉 dismiss。感谢反馈

**Comment by derekcoder** [comment]
新版本 3.4.0 已经发布，请体验体验。感谢反馈问题。
